num = [2 0 5]; den = [1 3 2];
        [r, p, k] = residue(num,den);
        disp(['(a) r = [',num2str(r.','  %0.5g'),']']);...
        disp(['    p = [',num2str(p.','  %0.5g'),']']);...
        disp(['    k = [',num2str(k.','  %0.5g'),']']);...
        num = [2 7 4]; den = [conv([1 1],conv([1 2],[1 2]))];
        [r, p, k] = residue(num,den);
        disp(['(b) r = [',num2str(r.','  %0.5g'),']']);...
        disp(['    p = [',num2str(p.','  %0.5g'),']']);...
        disp(['    k = [',num2str(k.','  %0.5g'),']']);...
        num = [8 21 19]; den = [conv([1 2],[1 1 7])];
        [r, p, k]= residue(num,den);
        [rad,mag]=cart2pol(real(r),imag(r));
        disp(['(c) r = [',num2str(r.','  %0.5g'),']']);...
        disp(['    p = [',num2str(p.','  %0.5g'),']']);...
        disp(['    k = [',num2str(k.','  %0.5g'),']']);...
        disp(['  rad = [',num2str(rad.','  %0.5g'),']']);...
        disp(['  mag = [',num2str(mag.','  %0.5g'),']']);
output1=r;
output2=p;
output3=k;
output4=rad;
output5=mag;